apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 851725282145.dkr.ecr.us-east-2.amazonaws.com/ats-backend:latest
          ports:
            - containerPort: 8502
          envFrom:
            - secretRef:
                name: backend-env

