name: CI/CD Pipeline for Frontend and Backend

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_BACKEND_REPO: ${{ secrets.ECR_BACKEND_REPO }}
  ECR_FRONTEND_REPO: ${{ secrets.ECR_FRONTEND_REPO }}

jobs:

  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_BACKEND_REPO
          aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_FRONTEND_REPO

      - name: Build and push backend image
        run: |
          docker build -t $ECR_BACKEND_REPO:latest ./backend
          docker push $ECR_BACKEND_REPO:latest

      - name: Build and push frontend image
        run: |
          docker build -t $ECR_FRONTEND_REPO:latest ./frontend
          docker push $ECR_FRONTEND_REPO:latest

  deploy:
    name: Deploy to Kubernetes from EC2
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Kubernetes via EC2 terminal
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.K8S_HOST }}
          username: ${{ secrets.K8S_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Configure AWS CLI on EC2
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set region ${{ env.AWS_REGION }}

            # Login to ECR from EC2
            aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_BACKEND_REPO
            aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_FRONTEND_REPO

            # Pull latest Docker images
            docker pull $ECR_BACKEND_REPO:latest
            docker pull $ECR_FRONTEND_REPO:latest

            # Write backend.env to file from GitHub Secrets
            echo "${{ secrets.BACKEND_ENV_FILE }}" > backend.env

            # Create or update Kubernetes Secret from .env file
            kubectl delete secret backend-env --ignore-not-found
            kubectl create secret generic backend-env --from-env-file=backend.env

            # Replace image placeholders in Kubernetes manifests
            sed -i "s|__BACKEND_IMAGE__|$ECR_BACKEND_REPO:latest|g" k8s/backend-deployment.yaml
            sed -i "s|__FRONTEND_IMAGE__|$ECR_FRONTEND_REPO:latest|g" k8s/frontend-deployment.yaml

            # Apply Kubernetes manifests
            kubectl apply -f k8s/backend-deployment.yaml
            kubectl apply -f k8s/backend-service.yaml
            kubectl apply -f k8s/frontend-deployment.yaml
            kubectl apply -f k8s/frontend-service.yaml

            # Cleanup Docker on EC2
            docker container prune -f
            docker image prune -af --filter "until=24h"
